This PR fixes issue with JSON decoder crashing on some properties & links
lxndrblz/forensicsim pull request #8
Opened 2022-05-23 12:58 UTC by mgeeky

Hi Alex!

Thanks for the terrific tool! I've fixed a bug that you left in reply chain decoding.
Some Teams properties.links JSONs are not strictly following JSON structure, causing json.loads to throw exception.

This is the faulty code snippet in `main.py`:

```
def decode_and_loads(properties):
    if (type(properties) is bytes):
        soup = BeautifulSoup(properties, features="html.parser")
        properties = properties.decode(soup.original_encoding)

    return json.loads(properties)
```

Example exception that was being thrown was related to unexpected characters in JSON streams.

```
Could not decode the following item in the reply chain (output is not deduplicated).
```

All it takes to mitigate the issue is to utilize `strict=False` parameter of PyJson.

Kind regards,
Mariusz.

2023-08-26 08:36 UTC, lxndrblz requested changes

2023-08-26 08:36 UTC, lxndrblz commented on requirements.txt
@mgeeky  Do you know, what the wxPython Package will be used for?

2023-08-26 08:40 UTC, lxndrblz requested changes

2023-08-26 08:40 UTC, lxndrblz commented on main.spec
@mgeeky Would you mind updating the [Travis CI file](https://github.com/lxndrblz/forensicsim/blob/main/.travis.yml) also to Python 3.10, as otherwise the automated builds would fail.

2024-01-07 10:08 UTC, KarelZe commented
Thanks @mgeeky for your suggestion. Will merge the suggested change with #30.

2024-01-07 10:08 UTC, closed without merging